### ISSUE TITLE
update GeneAtlas images to point to full-sized versions

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#1]
As described at https://www.wikidata.org/wiki/Property_talk:P692#How_about_using_full_size_image_instead_of_small_thumbnail.3F update all uses of the Gene Atlas Image property to use the full-sized version of the Gene Atlas image (e.g., https://www.wikidata.org/wiki/File:PBB_GE_ACTN3_206891_at_fs.png) instead of the thumbnail (e.g., https://www.wikidata.org/wiki/File:PBB_GE_ACTN3_206891_at_tn.png)

**Comment by stuppie** [comment]
https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/scripts/update_GeneAtlas_images.py
