### ISSUE TITLE
error in wikidatasparqlexamples for membrane proteins / colorectal cancer

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#10]
https://github.com/SuLab/wikidatasparqlexamples#retrieve-all-human-membrane-proteins-annotated-for-a-role-in-colorectal-cancer

returning an error: 
`Unknown error: Service URI https://query.wikidata.org/sparql is not allowed`

[execute](http://tinyurl.com/k9wdmeh)

**Comment by sebotic** [comment]
this one needs to be executed at sparql.uniprot.org because the Uniprot endpoint is still not allowed as a federated query target in the Wikidata endpoint. 

Just tested it at sparql.uniprot.org, works http://tinyurl.com/kmonkzw

**Comment by andrewsu** [comment]
Super, made this commit to note that... https://github.com/SuLab/wikidatasparqlexamples/commit/8a2bf7e7c4af6e72c0e750140b9000f47c2cc2be
