### ISSUE TITLE
Wikipathways bot is blocked on Jenkins but runs as expected else where

### ISSUE THREAD

**Issue by andrawaag** [SuLab/GeneWikiCentral#102]
I just noticed that the pathwaybot in Jenkins, is blocked [1], while it runs elsewhere. 

[1] http://jenkins.sulab.org/job/Wikipathways/10/console

**Comment by stuppie** [comment]
I saw this on GeneBot_microbes, ProteinBot_microbes, Wikipathways, GeneBot_microbes, ProteinBot_microbes also

$ cd /var/lib/jenkins
$ grep -rn -m1 "blocked" --include="*.log" | cut -f1 -d':'

`{'error': {'*': 'See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.', 'messages': [{'html': {'*': 'You do not have the permissions needed to carry out this action.'}, 'name': 'wikibase-api-permissiondenied', 'parameters': []}, {'html': {'*': '<p><b>Your IP address is in a range which has been blocked on all wikis.</b>\n</p><p>The block was made by <a class='external text' href='//meta.wikimedia.org/wiki/User:-revi'>-revi</a> (meta.wikimedia.org).\nThe reason given is <i><a href='https://meta.wikimedia.org/wiki/NOP' class='extiw' title='m:NOP'>Open proxy</a>: Leaky webhost: Contact <a href='https://meta.wikimedia.org/wiki/Special:Contact/stewards' class='extiw' title='m:Special:Contact/stewards'>stewards</a> if you are affected </i>.\n</p>\n<ul><li>Start of block: 12:39, 29 August 2018</li>\n<li>Expiration of block: 12:39, 29 August 2021</li></ul>\n<p>You can contact <a class='external text' href='//meta.wikimedia.org/wiki/User:-revi'>-revi</a> to discuss the block.\nYou cannot use the 'Email this user' feature unless a valid email address is specified in your <a href='/wiki/Special:Preferences' title='Special:Preferences'>account preferences</a> and you have not been blocked from using it.\nYour current IP address is 52.15.200.208, and the blocked range is 52.15.0.0/16.\nPlease include all above details in any queries you make.\n</p>'}, 'name': 'globalblocking-ipblocked-range', 'parameters': ['[//meta.wikimedia.org/wiki/User:-revi -revi]', 'meta.wikimedia.org', '[[m:NOP|Open proxy]]: Leaky webhost: Contact [[m:Special:Contact/stewards|stewards]] if you are affected <!-- Amazon Web Services -->', '12:39, 29 August 2018', '12:39, 29 August 2021', '52.15.200.208', '52.15.0.0/16']}, {'html': {'*': '<p><b>Your IP address is in a range which has been blocked on all wikis.</b>\n</p><p>The block was made by <a class='external text' href='//meta.wikimedia.org/wiki/User:-revi'>-revi</a> (meta.wikimedia.org).\nThe reason given is <i><a href='https://meta.wikimedia.org/wiki/NOP' class='extiw' title='m:NOP'>Open proxy</a>: Leaky webhost: Contact <a href='https://meta.wikimedia.org/wiki/Special:Contact/stewards' class='extiw' title='m:Special:Contact/stewards'>stewards</a> if you are affected </i>.\n</p>\n<ul><li>Start of block: 12:39, 29 August 2018</li>\n<li>Expiration of block: 12:39, 29 August 2021</li></ul>\n<p>You can contact <a class='external text' href='//meta.wikimedia.org/wiki/User:-revi'>-revi</a> to discuss the block.\nYou cannot use the 'Email this user' feature unless a valid email address is specified in your <a href='/wiki/Special:Preferences' title='Special:Preferences'>account preferences</a> and you have not been blocked from using it.\nYour current IP address is 52.15.200.208, and the blocked range is 52.15.0.0/16.\nPlease include all above details in any queries you make.\n</p>'}, 'name': 'globalblocking-ipblocked-range', 'parameters': ['[//meta.wikimedia.org/wiki/User:-revi -revi]', 'meta.wikimedia.org', '[[m:NOP|Open proxy]]: Leaky webhost: Contact [[m:Special:Contact/stewards|stewards]] if you are affected <!-- Amazon Web Services -->', '12:39, 29 August 2018', '12:39, 29 August 2021', '52.15.200.208', '52.15.0.0/16']}, {'html': {'*': '<p><b>Your IP address is in a range which has been blocked on all wikis.</b>\n</p><p>The block was made by <a class='external text' href='//meta.wikimedia.org/wiki/User:-revi'>-revi</a> (meta.wikimedia.org).\nThe reason given is <i><a href='https://meta.wikimedia.org/wiki/NOP' class='extiw' title='m:NOP'>Open proxy</a>: Leaky webhost: Contact <a href='https://meta.wikimedia.org/wiki/Special:Contact/stewards' class='extiw' title='m:Special:Contact/stewards'>stewards</a> if you are affected </i>.\n</p>\n<ul><li>Start of block: 12:39, 29 August 2018</li>\n<li>Expiration of block: 12:39, 29 August 2021</li></ul>\n<p>You can contact <a class='external text' href='//meta.wikimedia.org/wiki/User:-revi'>-revi</a> to discuss the block.\nYou cannot use the 'Email this user' feature unless a valid email address is specified in your <a href='/wiki/Special:Preferences' title='Special:Preferences'>account preferences</a> and you have not been blocked from using it.\nYour current IP address is 52.15.200.208, and the blocked range is 52.15.0.0/16.\nPlease include all above details in any queries you make.\n</p>'}, 'name': 'globalblocking-ipblocked-range', 'parameters': ['[//meta.wikimedia.org/wiki/User:-revi -revi]', 'meta.wikimedia.org', '[[m:NOP|Open proxy]]: Leaky webhost: Contact [[m:Special:Contact/stewards|stewards]] if you are affected <!-- Amazon Web Services -->', '12:39, 29 August 2018', '12:39, 29 August 2021', '52.15.200.208', '52.15.0.0/16']}], 'code': 'permissiondenied', 'info': 'You do not have the permissions needed to carry out this action.'}, 'servedby': 'mw1221'}`

These are all running with MicrobeBot or PathwayBot. I emailed the Wikimedia stewards <stewards@wikimedia.org> and had MicrobeBot added

```
Dear Greg S,
ProteinBoxBot already has Global IP Exemption flag. I've granted the permission to MicrobeBot.
Yours sincerely,
Sihyeon Ryu
Wikimedia Stewards
```

**Comment by stuppie** [comment]
To Do: email to add PathwayBot also

**Comment by andrawaag** [comment]
>  Dear
> 
>  Andra Waagmeester,
> 
> Thank you for your email. This is an automatically generated response to inform you that your message has been received.
> 
> A member of the steward team will respond as soon as possible. If your query is urgent, please consider contacting a steward on IRC:  https://meta.wikimedia.org/wiki/IRC.
> 
> Your ticket number is #2019022110004319.
> 
> Regards,
> 
> The Wikimedia Stewards

**Comment by andrawaag** [comment]
Since I did not get a reply I reached out to the stewards at IRC. The email address stewards@wikimedia.org  is not monitored that often. I was suggested to issue a request online. Which I did [here](https://meta.wikimedia.org/wiki/Steward_requests/Global_permissions#Global_IP_block_exempt_for_Pathwaybot)

**Comment by andrawaag** [comment]
Global IP block exempt has been granted
