### ISSUE TITLE
wikidatasparqlexamples for indole / urogenital tract returning zero results

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#11]
https://github.com/SuLab/wikidatasparqlexamples#request-all-organisms-that-are-located-p276-in-the-female-urogential-tract-wdq5880-and-that-have-a-gene-with-product-p1056-indole-wdq319541

returns zero results -- did something in the data model change?

**Comment by putmantime** [comment]
Succu removed the location = vagina claim.  I just restored it for e coli and it works.  Will do the same for prevotella
