### ISSUE TITLE
Load ClinGen gene-disease validity data

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#116]
https://search.clinicalgenome.org/kb/gene-validity/

Curated / semi-curated source of gene-disease links, currently with 747 entries

Evidence category | Count 
-- | --
Definitive | 356
Limited | 139
No Reported Evidence | 81
Moderate | 73
Disputed | 69
Strong | 22
Refuted | 7
-- | --
Grand Total | 747

seems like the latest data is always available at https://search.clinicalgenome.org/kb/gene-validity.csv; I see no evidence that an API is available or planned.

**Comment by andrewsu** [comment]
explicitly CC0 licensed! https://clinicalgenome.org/docs/terms-of-use/

**Comment by andrewsu** [comment]
also use this as an excuse to update documentation with WDI and at http://learningwikibase.com/data-import/.  Coordinate with @andrawaag...

**Comment by sabahzero** [comment]
https://github.com/sabahzero/WikiData-ClinGenBot

**Comment by sabahzero** [comment]
@andrewsu @andrawaag following up to check/confirm if this is now closed?

**Comment by sabahzero** [comment]
https://github.com/SuLab/scheduled-bots/tree/master/scheduled_bots/clingen
