### ISSUE TITLE
Load ClinGen variant pathogenicity data

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#117]
https://erepo.clinicalgenome.org/evrepo/

Currently has 684 variant annotations for 18 unique diseases

evidence breakdown:

Evidence category | Count 
-- | --
Benign | 200
Pathogenic | 191
Likely Pathogenic | 122
Uncertain Significance | 100
Likely Benign | 71
-- | --
Grand Total | 684

**Comment by andrewsu** [comment]
explicitly CC0 licensed! https://clinicalgenome.org/docs/terms-of-use/

**Comment by andrawaag** [comment]
first draft schema proposal: https://www.wikidata.org/wiki/EntitySchema:E63

**Comment by andrawaag** [comment]
Moved the issue to https://github.com/SuLab/scheduled-bots/issues/37 for further developement
