### ISSUE TITLE
create mechanism to execute "Data Unit Tests" 

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#12]
We currently have two sparql queries at https://github.com/SuLab/wikidatasparqlexamples#data-unit-tests that *should* always return zero results.  Would be nice to automate to confirm they stay at zero.  (One result is currently non-zero, looks like it's been that way for several months since [this edit](https://www.wikidata.org/w/index.php?title=Q2914458&diff=417690141&oldid=417689953)...)

**Comment by stuppie** [comment]
Maintenance queries are here:
https://www.wikidata.org/wiki/User:ProteinBoxBot/Maintenance_Queries

I have a job running on jenkins that runs these queries every week:
http://jenkins.sulab.org/job/Maintenance_Query/

Script source:
https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/query_tester/tester.py

Results Page:
https://www.wikidata.org/wiki/User:ProteinBoxBot/Maintenance_Query_Results
