### ISSUE TITLE
Use Uniprot primary label for labelling protein items in Wikidata

### ISSUE THREAD

**Issue by sebotic** [SuLab/GeneWikiCentral#13]
While doing some entity mapping from scientific data to Wikidata, I came across the problem that the scientific data did not have identifiers for the proteins, which is not good, but what they did have is the exact Uniprot primary protein name label, so label matching would be possible.

The issue is that Wikidata frequently does not use these Uniprot primary labels, but some more verbose derivative. (nor can they be found in the aliases) Example (https://www.wikidata.org/wiki/Q21108705) with http://www.uniprot.org/uniprot/Q13003

So it would be helpful if the Uniprot primary label was at least part of the aliases, so it could be found while doing a string based mapping. (which is frequently the only mapping possible for data extracted from a paper).

**Comment by stuppie** [comment]
Looks like it is (at least in this example) in the "other_names" field in [mygene](https://mygene.info/v3/gene/2899)
Easy fix, to here: https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/geneprotein/ProteinBot.py#L121

**Comment by sebotic** [comment]
ok, if that's readily available in mygene

You can also get the labels with this SPARQL query from sparql.uniprot.org

```sparql
PREFIX up:<http://purl.uniprot.org/core/> 
PREFIX taxon:<http://purl.uniprot.org/taxonomy/> 
PREFIX skos:<http://www.w3.org/2004/02/skos/core#> 

SELECT ?protein ?name WHERE {
	?protein a up:Protein .
	?protein up:organism taxon:9606 .
        ?protein up:recommendedName ?recommended .
	?recommended up:fullName ?name .
}
```

**Comment by stuppie** [comment]
Implemented with commits: https://github.com/SuLab/wdbiothings/commit/b76386135eb10d8717fc1aac4d50c3e1d7c620e4 https://github.com/SuLab/wdbiothings/commit/e9ceb27d163b1e0528cfc8cfb2c0093ed12dd38c https://github.com/SuLab/scheduled-bots/commit/23a6051066bb6b39deba897dce3f04206f5b350d
Example revision: https://www.wikidata.org/w/index.php?title=Q21100363&diff=prev&oldid=486569401
