### ISSUE TITLE
Gene Wiki article creator broken

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#14]
A user requested creation of a gene wiki page for FCHO1 (Entrez Gene 23149).  The Gene Wiki BioGPS plugin goes to http://genewiki.sulab.org/map/wiki/23149, which then redirects to http://genewiki.sulab.org/map/wiki/23149/genewiki.wiki.views.article_create which returns 404.

If @julialturner is still around it would be great if you can take a look and see if it's something simple.  If we don't hear back in a couple days, we should just take this one on ourselves...

**Comment by andrewsu** [comment]
On fix, someone should also create the FCHO1 page and/or follow up with this user https://en.wikipedia.org/w/index.php?title=User_talk%3AProteinBoxBot%2FPhase_3&type=revision&diff=780219122&oldid=653967701

**Comment by julialturner** [comment]
@andrewsu I can create the page with my local copy of code and will see if there is an easy fix for the page creation.

**Comment by julialturner** [comment]
It seems this is something to do with the server configuration.  Did it ever work after everything was moved over?

**Comment by andrewsu** [comment]
Thanks @julialturner -- not sure if we tested the article creation feature after migration.  Just want to confirm as we try to debug server-side, is the redirect to http://genewiki.sulab.org/map/wiki/23149/genewiki.wiki.views.article_create correct?  Or should that be mapping to another URL?

**Comment by julialturner** [comment]
@andrewsu the redirect should be http://genewiki.sulab.org/wiki/article/create/23149/

**Comment by goodb** [comment]
@julialturner thanks for chiming in.  Could you confirm that this line is correct and matches your local situation?  (line 29 in mapping/views.py ) .  I believe thats the line that starts the redirect problem.  
https://github.com/SuLab/GeneWikiCentral/blob/master/genewiki/genewiki/mapping/views.py#L29

Should go to http://genewiki.sulab.org/wiki/article/create/23149/ but instead goes to 
http://genewiki.sulab.org/map/wiki/23149/genewiki.wiki.views.article_create

Seems like it needs some indication to go up to the root context to find the URL pattern with name = article_create ?  (here https://github.com/SuLab/GeneWikiCentral/blob/master/genewiki/genewiki/wiki/urls.py ) ??

**Comment by julialturner** [comment]
@goodb yes my line 29 in mapping/views.py is the same

**Comment by goodb** [comment]
Okay thanks @julialturner .  @putmantime is looking into it.  Most likely something about the django/nginx server configuration I guess.

**Comment by goodb** [comment]
Update. multiple problems actually.  #1 python not importing gene wiki module.  Fixed by @putmantime .  #2 Looks like cross-origin request problem:  Safari:  "Refused to display 'http://genewiki.sulab.org/wiki/article/create/23150/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.  #3 its not actually reading any password file so once we get it to execute will fail to make the wikidata write.  Hopefully will cure these tomorrow...

**Comment by goodb** [comment]
@putmantime For the X-frame-options error I think this is a result of the latest django release being made 'safer' by default.  See https://docs.djangoproject.com/en/1.11/ref/clickjacking/#setting-x-frame-options-for-all-responses  .  Its defaulting to SAMEORIGIN, blocking all attempts to render the content in an iframe like biogps.  Looks like it needs the @xframe_options_exempt decorator added to the views that we want to be able to show in iframe.  (Tried fixing this at nginx conf level, but needs django-specific fix)

**Comment by putmantime** [comment]
@goodb The decorator fixed it and the prompt to create a new article is now rendering in GPS.  I am now trying to fix the password issue.  Is there a different set of credentials for writing to wikipedia?

**Comment by putmantime** [comment]
Update.  Article creator is now functional.
Fixes implemented:
1. Python import of article_create view  into mapping view.
     -less than ideal Python path append to allow import
     -restructuring of project for proper python path imports would be optimal
2. Cross origin request error for rendering in BioGPS;
    -added '@xframe_options_exempt' decorator to article create view
3. password import for PBB:
    -created a pbb_secret.py file with password and user name
    - imported into /wiki/views.py and wiki/textutils.py for wikipedia article and interwikilink creation.
4. created .gitignore file
    -added django secret key to pbb_secret.py and imported into django settings.py
    -added pbb_secret.py path to .gitignore

**Comment by goodb** [comment]
plugin functional once more.  closing.
