### ISSUE TITLE
What do we do with deprecated genes?

### ISSUE THREAD

**Issue by stuppie** [SuLab/GeneWikiCentral#15]
There are 1473 human genes in wikidata that are deprecated (at least by entrez). Should they be marked as such?
I know we've discussed this before, but I don't think we reached a consensus?

Example: https://www.wikidata.org/wiki/Q20782867
some more entrez ids for example: 100422181,105370493,100533890,100422182,105377780,100421864,653365,100422127,100288864,100422159,105371827,100507577,105378176,101927617,729268,29053,100418654,100127889,100421887,100418651

And 7034 deprecated mouse genes (out of 75k)

**Comment by sebotic** [comment]
As I suggested way back in time, I would propose those for deletion, bc these are not useful and create confusion if formatter urls don't work, etc. 

I think we strive to providing the most current view of a certain domain of knowledge, therefore, if someone needs old builds of entrez gene or whatever, they should download that manually.

**Comment by sebotic** [comment]
how many of them are linked to proteins?

**Comment by stuppie** [comment]
19 encode for a protein. Among them for example: https://www.wikidata.org/wiki/Q18049277 , where the entrez id [117153](https://www.ncbi.nlm.nih.gov/gene/117153) was discontinued and replaced with [4253](https://www.ncbi.nlm.nih.gov/gene/4253), (which exists in [wd](https://www.wikidata.org/wiki/Q18029091)), according to Entrez, but both still exist in Ensembl

**Comment by sebotic** [comment]
well, the the disagreement btwn Ensembl and Entrez cannot be resolved by us.

**Comment by goodb** [comment]
Generally I suggest that if the primary source you are drawing from deprecates a record (gene or ontology term etc.) you delete it from wikidata - unless other people are using it, particularly if its connected to a wikipedia article.  In that latter case, manual intervention is suggested.

**Comment by stuppie** [comment]
Added gene deletion bot: https://github.com/SuLab/scheduled-bots/commit/85e5155c7d4469128f70a30ee2775a64a403e369
Compiles a list of genes that are in wikidata but not in mygene.info (based on Entrez ID) and then submits them for deletion
