### ISSUE TITLE
fix link to jenkins

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#22]
Broken link in https://github.com/SuLab/GeneWikiCentral/blob/master/README.md#scheduled-bots and https://github.com/SuLab/scheduled-bots/blob/master/README.md#scheduled-bots.  we should also set up jenkins.sulab.org (or something similar) while we're at it...

**Comment by stuppie** [comment]
http://jenkins.sulab.org/ is set up
