### ISSUE TITLE
Add WDI to bot creation page 

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#23]
The people who have used WDI seem to like it.  We should make it known to more people.  Start by posting more info here:

https://www.wikidata.org/wiki/Wikidata:Creating_a_bot

**Comment by andrewsu** [comment]
From Daniel M comment in grant proposal brainstorming gdoc: "put up some Jupyter notebooks with example workflows on PAWS."

**Comment by Daniel-Mietchen** [comment]
Here's what I have so far:
https://paws.wmflabs.org/paws/user/Daniel_Mietchen/notebooks/Fatameh-testing/fatameh-wrapper.ipynb .
I have tried using WDI directly but got lost in the documentation.

**Comment by stuppie** [comment]
@Daniel-Mietchen How do I make a paws notebook public?

**Comment by stuppie** [comment]
Posted a small summary here: https://www.wikidata.org/wiki/Wikidata:Creating_a_bot#Wikidata_Integrator
It could use a little more documentation
