### ISSUE TITLE
create sparql query that filters on contradictory claims

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#28]
For third-party consumers, trusting the data in wikidata is a big deal.  As one metric of trust, one can imagine a query that filters out any assertion that has multiple contradictory statements.  We should create one such example that demonstrates this principle and add it to wikidatasparqlexamples.

**Comment by stuppie** [comment]
Putting here for now, will include with #19
http://tinyurl.com/y892oepd

**Comment by stuppie** [comment]
https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Example_demonstrating_how_to_filter_out_contradictory_claims
