### ISSUE TITLE
create sparql query that filters out unreferenced claims

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#29]
For third-party consumers, trusting the data in wikidata is a big deal.  As one metric of trust, one can imagine a query that filters out any claims that has no reference.  We should create one such example that demonstrates this principle and add it to wikidatasparqlexamples.

**Comment by stuppie** [comment]
Putting here for now, will include with https://github.com/SuLab/GeneWikiCentral/issues/19
http://tinyurl.com/y8xew8an

**Comment by stuppie** [comment]
https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Example_demonstrating_how_to_filter_out_unreferenced_claims

**Comment by andrewsu** [comment]
The example query at https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Example_demonstrating_how_to_filter_out_unreferenced_claims looks great.  One request for enhancement though.  Can the "hasRef" column also indicate the source of the reference (eg NDF-RT) if one exists?

**Comment by stuppie** [comment]
Updated
