### ISSUE TITLE
create SPARQL query that incorporates determination method

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#35]
I'd like an example query added to https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples that incorporates "determination method" (P495).  For example, of all "genetic association" (P2293) claims linking gene to disease, how many are from GWAS versus other methods?

**Comment by stuppie** [comment]
https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Example_demonstrating_how_to_retrieve_determination_method_qualifiers
https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Example_counting_statements_by_their_determination_method
