### ISSUE TITLE
add reference for [operon] [has part] [gene] statements

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#36]
For example, the triple [Operon 310](https://www.wikidata.org/wiki/Q24286349) / [has part (P527)](https://www.wikidata.org/wiki/Property:P527) / [adenylosuccinate lyase lmo1773](https://www.wikidata.org/wiki/Q23238170) is currently unreferenced.  (Though the reverse [adenylosuccinate lyase lmo1773](https://www.wikidata.org/wiki/Q23238170) / [part of (P361)](https://www.wikidata.org/wiki/Property:P361) / [Operon 310](https://www.wikidata.org/wiki/Q24286349) looks to be correctly referenced.)

**Comment by putmantime** [comment]
References added to Operon 310.
