### ISSUE TITLE
add cytogenetic map location to gene items

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#38]
Per [this request](https://www.wikidata.org/w/index.php?title=Wikidata_talk%3AWikiProject_Molecular_biology&type=revision&diff=513769580&oldid=505514569), add cytogenetic map location to gene items.  (Perhaps limited to human genes?)  Shows up in mygene.info under "map_location" key (e.g., [CDK2](http://mygene.info/v3/gene/1017) --> 12q13.2)

**Comment by andrewsu** [comment]
see the cool visualization of genomic position described at https://en.wikipedia.org/wiki/Module_talk:Infobox_gene#Gene_location_column_added (now incorporated into the infobox module).  Cytogenetic position could undoubtedly be added without too much effort...

**Comment by stuppie** [comment]
https://www.wikidata.org/wiki/Wikidata:Property_proposal/Cytogenetic_location

**Comment by stuppie** [comment]
https://github.com/SuLab/scheduled-bots/commit/ffa65934013f107110cdbfc22b89d467f3cab86c
https://github.com/SuLab/wdbiothings/commit/ee1ec702b933c2fba79b0987a7099bd08f8b7da3

**Comment by andrewsu** [comment]
just reopening this ticket so that when the first run is complete, we can notify the user so s/he can add the info to the infobox gene module...

**Comment by stuppie** [comment]
This has run for humans, and notified Was a bee
https://en.wikipedia.org/wiki/Module_talk:Infobox_gene#Gene_location_column_added
