### ISSUE TITLE
Disease links to GARD

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#41]
Per email/context from James Heilman below, add links from disease items to GARD.

As a starting point, we need to figure out

- [ ] is there a mapping table available?
- [ ] does a suitable property already exist?

> ---------- Forwarded message ----------
> From: James Heilman 
> Subject: WD help
> To: Andrew Su 
> 
> Hey Andrew
> 
> We have a new classification / external resources link box at the end of articles such as you can see here https://en.wikipedia.org/wiki/Gout#External_links
> 
> Interested in adding some more ELs to WD and wondering if you can help with that? For example wanting to add:
> 
> 1) cdc.gov links for diseases https://www.cdc.gov/az/a.html
> 
> 2) Rare Disease Database https://rarediseases.org/for-patients-and-families/information-resources/rare-disease-information/ (1200 items)
> 
> 3) GARD links https://rarediseases.info.nih.gov/diseases
> 
> 4) GHD https://ghr.nlm.nih.gov/condition
> 
> Will then pull these ELs directly from WD similar to how we are doing it do patients.info Possible?

**Comment by andrewsu** [comment]
I'm in discussions with NCATS folks on data licensing

**Comment by stuppie** [comment]
Property proposal here: https://www.wikidata.org/wiki/Wikidata:Property_proposal/GARD

**Comment by stuppie** [comment]
https://tools.wmflabs.org/mix-n-match/#/catalog/583

**Comment by andrewsu** [comment]
FYI, progress is being made on this front.  I have API access now, which has enough information to make these additions: https://www.wikidata.org/w/index.php?title=Q8282&type=revision&diff=624596347&oldid=623826538 (example on Addison's Disease). 

Also, GARD folks are interested in contributing their disease-normalized database of FDA-approved drugs for orphan diseases (available at https://rarediseases.info.nih.gov/diseases/fda-orphan-drugs).

Their internal licensing discussions are ongoing (but seem promising...)
