### ISSUE TITLE
[Question] how to extract gene and omics data from Wikidata

### ISSUE THREAD

**Issue by floatingpurr** [SuLab/GeneWikiCentral#45]
Hello there! Excuse me for this trivial question but I'm quite new to the Wikidata life sciences world (your work on *-omics is great!).

I'm trying to extract relevant data related to life sciences from Wikidata compliant to w3c specifications. I think that using Wikidata as central HUB is a more effective and concrete way to leverage Linked Data for knowledge exploration. What I need is a collection of RDF statements describing Human Genome, diseases, proteins, and related annotations with compliant RDF(S)/OWL statements. I found [`genewiki.owl`](https://github.com/SuLab/GeneWikiCentral/blob/master/owl/genewiki.owl) and I guess that is the ontology describing life sciences data models on Wikidata.

I'm trying to download data via the Wikidata SPARQL enpoint through a bunch of custom queries but I'm wondering if that is "the way". Is there a more proper and faster approach to download a dump of data related to the `genewiki.owl` model?

Thank you!

Edit:

I've just noticed that classes URIs in `genewiki.owl` are note the same of wikidata, but I think they are the same classes. Besides, in that file there are not all properties used in Wikidata (e.g., genomic start/end). Isn't there a comprehensive OWL model?

Bye!

**Comment by stuppie** [comment]
Hi @superciccio14, Thanks for your interest! As Wikidata is very "open-world", we do not have a strict ontology describing the relationships used. genewiki.owl is an attempt at that, but as you saw, is not complete. Are you looking for information about specific concepts, item, or properties? Or do you want 'everything' related to biomedical sciences in Wikidata? 

If you are asking specific questions, SPARQL queries are "the way". [Here](https://www.wikidata.org/wiki/User:ProteinBoxBot#/media/File:Gene_wiki_world_network.png) is a little "map" of this biomedical space as of June 2017, that was made using SPARQL queries and some manual filtering, that should help you write the targeted queries. [Here](https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples) are some example queries to guide you also. 

If you'd like to download everything, you can either go through the Wikidata dumps are write "traversal" sparql queries that just get everything connected to an item ([for example](https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Retrieve_reverse.2F.22what_links_here.22_statements_.28statements_where_the_item_is_the_object.29)).

Let me now if this helps!

**Comment by stuppie** [comment]
Another example "traversal" query. This gets all statements on a set of items (for one property), including references and qualifiers.

```
select ?item ?qval ?pq ?sid ?v ?ref ?pr ?rval where {
  values ?item {wd:Q14911732 wd:Q21129787}

  ?item p:P644 ?sid .

  ?sid ps:P644 ?v .
  OPTIONAL {
    ?sid ?pq ?qval .
    FILTER(STRSTARTS(STR(?pq), "http://www.wikidata.org/prop/qualifier/P"))
  }
  OPTIONAL {
    ?sid prov:wasDerivedFrom ?ref .
    ?ref ?pr ?rval .
    FILTER(STRSTARTS(STR(?pr), "http://www.wikidata.org/prop/reference/P"))
  }
}
```

**Comment by superciccio14** [comment]
Hi @stuppie and thanks for your kind replies! I'll definitely try your hints to extract relevant biological Knowledge from Wikidata. 

If you are interested in the reason of my question, here there is the long story short. My goal is building a semantic annotation platform for biological entities related to genomic and drug-resistance data. I explored other semantic/linked data effort like [this](http://linkedlifedata.com/) or [this one](http://bio2rdf.org/), but they seem outdated and I think they arrived to a dead end. Also the [LOD](http://lod-cloud.net/) had seemed to me a good starting point but, in practice, it's very hard to manually integrate such datasets. Finally, I came across [your paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4795929/), and that's the reason of my first question :smile: 

Probably, "the way" - as you suggested - is getting data from Wikidata and link'em to my own ontology, eventually adding locally new classes or properties. In that way, I can always refer back to Wikidata and to its xrefs, leveraging a very huge and active KB.

**Comment by andrawaag** [comment]
@floatingpurr If you are using existing name spaces in your local data, mapping properties like those from [SKOS](https://www.w3.org/TR/skos-reference/#mapping) can help in providing links to Wikidata. 
Another approach I am using more and more is to actually use the Wikidata namespace as local namespace. The Wikidata properties can be used as predicates in linked data

**Comment by floatingpurr** [comment]
Hello @andrawaag, yes the SKOS vocabulary can be definitely used to map my local URIs to their equivalent in wikidata. I've recently performed some tests with the second approach (i.e., directly using wikidata resources to tag my data). In both cases, federated queries have to be taken into account to enrich the local knowledge, as you described [here](http://sulab.org/2017/07/integrating-wikidata-and-other-linked-data-sources-federated-sparql-queries/).

_A little off topic: are new data contributions for life sciences welcome in wikidata?_

**Comment by andrewsu** [comment]
> A little off topic: are new data contributions for life sciences welcome in wikidata?

Absolutely! Data licenses tend to be the key sticking issue. But if you have a CC0-licensed resource in mind that you'd like to load, we'd love to share our knowledge/experience/tools with you.

**Comment by floatingpurr** [comment]
Hello @andrewsu, thank you very much for your answer. At the moment, I have not clear options in mind. Maybe COSMIC could be a good dataset, but it [does not seem](http://cancer.sanger.ac.uk/cosmic/license) explicitly CC0-licensed. Another option could be to insert transcripts as entities, thus encouraging further annotations about them. Indeed, if I am not wrong, in the actual data landscape they are just listed as external IDs and the predicate/property `encodes` ([`P688`](https://www.wikidata.org/wiki/Property:P688)) has proteins as objects but not RNAs.

I'll definitely get back to you as soon as I have a clear proposal in mind. Thank you once again for your kind support and for your great work : )
