### ISSUE TITLE
create Translator section for SPARQL_examples

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#46]
@stuppie can you go through the [CQ notebooks for translator](https://github.com/NCATS-Tangerine/cq-notebooks) and transfer the SPARQL queries from any existing wikidata-based solutions to https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples ? If less than three such queries exist, can you bring the number up to three by picking additional CQs that can be addressed using Wikidata?  Partial solutions are fine.

**Comment by stuppie** [comment]
https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#NCATS_Translator_Queries
