### ISSUE TITLE
remove last remnants of Template:PBB from Wikipedia pages

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#51]
There are 100 instances left of Template:PBB in the main namespace at Wikipedia.  We need to get those replaced with Template:Infobox_gene

https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Template:PBB&namespace=0&limit=100

**Comment by julialturner** [comment]
I can remove these if needed.

Best,
Julia

**Comment by andrewsu** [comment]
@julialturner yes please, that would be great!

**Comment by julialturner** [comment]
I have gone through this list of 100 and made the necessary changes to update to Infobox_gene

**Comment by andrewsu** [comment]
thanks!
