### ISSUE TITLE
merge presentations/publications tables in Wikidata documentation

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#54]
I propose that https://www.wikidata.org/wiki/User:ProteinBoxBot#Publications.2C_presentations.C2.A0 be merged into https://www.wikidata.org/wiki/Wikidata:WikiProject_Molecular_biology/Presentations

**Comment by stuppie** [comment]
https://www.wikidata.org/wiki/Wikidata:WikiProject_Gene_Wiki/Presentations
