### ISSUE TITLE
Wikipedia Category to collect Gene Wiki reviews

### ISSUE THREAD

**Issue by TS404** [SuLab/GeneWikiCentral#56]
There should be a category in Wikipedia to collect all the articles that have been updated as a result of the gene wiki review series. This could be similar to: [Category:Wikipedia_articles_with_sections_published_in_WikiJournal_of_Medicine](https://en.wikipedia.org/wiki/Category:Wikipedia_articles_with_sections_published_in_WikiJournal_of_Medicine) and would likely sit within the [Category:Externally_peer_reviewed_articles
](https://en.wikipedia.org/wiki/Category:Externally_peer_reviewed_articles)

Conceivably, a template could also be added to the talk page or article page stating something along the lines of:
`"the version as of on {{{date}}} was updated by an external expert and subjected to formal peer review by the journal 'Gene', the corresponding academic article can be found {{{here}}}.<ref>{{{citation}}}</ref>"`

See for possible inspiration: [Template:Academic_peer_reviewed](https://en.wikipedia.org/wiki/Template:Academic_peer_reviewed)

Although the Academic_peer_reviewed template was designed for circumstances where the same wording was published in both Wikipedia and the Journal, it could possibly be updated to have a wording option that fit the gene wiki circumstances.

**Comment by gtsueng** [comment]
Would something like this work?

> "the {{{date}}} version of this article was updated by an external expert under a dual publication model. Under this model, external experts are required to update corresponding Wikipedia articles while publishing a peer-reviewed, invited review article for the journal 'Gene'.  The corresponding academic review article can be found {{{here}}. <ref>{{{citation}}}<ref>

As mentioned, the Academic_peer_reviewed template was designed for verbatim text between the peer reviewed article and the wiki entry. Any template we use should be different enough to see this distinction.

**Comment by gtsueng** [comment]
A [template](https://en.wikipedia.org/wiki/Template:Academic-written_review) was created which can be added to the talk or article page and can be found via: [Category:Wikipedia articles with corresponding academic peer reviewed articles](https://en.wikipedia.org/wiki/Category:Wikipedia_articles_with_corresponding_academic_peer_reviewed_articles)

An example of the template on an article page is [available here.](https://en.wikipedia.org/wiki/Binding_immunoglobulin_protein)
