### ISSUE TITLE
Add instance-of high-level type where missing

### ISSUE THREAD

**Issue by goodb** [SuLab/GeneWikiCentral#6]
Its very useful for application building and query to be able to know basically what an entity is about without having to traverse class hierarchies.  Specifically for each ontology term we maintain, add an  appropriate instanceOf relation:
 instanceOf {biological process or molecular function or cellular component or Disease or Evidence Kind...}
Also, change the subclass relations on genes and proteins to instance relations.  
(gene instance) instanceOf gene  (replacing subclass here)
(protein instance) instanceOf protein (replacing subclass here)

**Comment by stuppie** [comment]
What of our stuff will this break? Should update these first.

1. Gene/protein infoboxes @julialturner
2. Wikigenomes @putmantime
3. ...

Do we have to worry about breaking other things? Notify people? [Here](https://www.wikidata.org/wiki/Wikidata:Project_chat) maybe

**Comment by julialturner** [comment]
@stuppie would you if you are adding P31 and not removing P279, there shouldn't be a problem.  Either way I just need to update one line of code.

**Comment by stuppie** [comment]
Type | Done | Person | Query
------------ | -------------| -------------| -------------
Gene | No | Me
Protein | No | Me
Chromosome | No | Me
GO | No | Sebastian
Disease | Yes | | http://tinyurl.com/km9sl83
Protein family/domain | Yes |
Drug | Yes | http://tinyurl.com/l5ffm4t

**Comment by goodb** [comment]
@stuppie looks like gene is done? awaiting protein and Chromosome, yes ?

**Comment by stuppie** [comment]
Yes. I also need to fix the other non-protein coding items: 
non-coding RNA (Q427087)
transfer RNA (Q201448)
pseudogene (Q277338)
small nucleolar RNA (Q284416)
small nuclear RNA (Q284578)
ribosomal RNA (Q215980)

I will make these instance of one of the above items

**Comment by stuppie** [comment]
Still need to clean up some proteins, will make an issue in a sec
