### ISSUE TITLE
Create WikiProject Gene Wiki

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#65]
https://www.wikidata.org/wiki/User:ProteinBoxBot currently serves as a main coordination page for the Gene Wiki project, but as we divide up our activities into multiple bot accounts, I think it makes sense to create a parent wiki page.  I suggest https://www.wikidata.org/wiki/Wikidata:WikiProject_Gene_Wiki, which then would link out to all of our bot accounts...

**Comment by andrawaag** [comment]
I started a stub at https://www.wikidata.org/wiki/Wikidata:WikiProject_Gene_Wiki and also a stub on Disease properties https://www.wikidata.org/wiki/Wikidata:WikiProject_Gene_Wiki/Properties

**Comment by andrawaag** [comment]
I proposed a draft menu structure as tabs on the project page. 
https://www.wikidata.org/wiki/Wikidata:WikiProject_Gene_Wiki Comment and suggestions on changes in the tab structure are welcome. 
I put special effort into creating a documentation page of a bot (i.e. Pathwaybot: https://www.wikidata.org/wiki/User:Pathwaybot) This page is linked under the tab bots on the WikiProject Gene Wiki.

**Comment by andrewsu** [comment]
Thanks Andra.  It looks to me that the sub-tabs under "Primary Sources" and "Bots" are the same (links to ProteinBoxBot, MicrobeBot, SoCalChemBot, etc.).  Is that intentional?  I think that should be under "Bots" but not "Primary Sources".  Not entirely sure what I'd expect to see under "Primary Sources" -- what were you thinking would be there?

**Comment by andrawaag** [comment]
The idea was that the tab "Primary sources" would capture the description of the different repositories being sourced (e.g Reactome and Wikipathways under the tab Pathwaybot), whereas the "Bots" would describe the bot logic and possibly capture curation reports. 

However, I can see that this is confusing. Maybe removing the tabs and simply add a list all the resources being synced with Wikidata by us is sufficient.

**Comment by andrewsu** [comment]
what do you think of having Primary Sources on each bot page itself?  A structure something like this?

```
Project Gene Wiki
  --> Bots
      --> User:ProteinBoxBot
         --> Primary Sources
         --> Bot tasks
         --> Operators
      --> User:Microbebot
         --> Primary Sources
         --> Bot tasks
         --> Operators
      --> ...
   --> WDI
   --> Example queries
```

**Comment by andrawaag** [comment]
The above structure has been implemented. Still working on completing the individual pages. Pathwaybot is more or less complete due to it serving as a landing page for our Combine presentation on the Pathwaybot
