### ISSUE TITLE
Add all AGR genomes to wikidata

### ISSUE THREAD

**Issue by goodb** [SuLab/GeneWikiCentral#7]
Saccharomyces 
C elegans, 
drosophila, 
Zebrafish,
Mouse 
Rat 
https://genestogenomes.org/model-organism-databases-join-forces-announcing-the-alliance-of-genome-resources/

**Comment by stuppie** [comment]
Organism | Organism WD | Property | Genome in WD?
------------ | ------------- | ------------- | -------------
Saccharomyces|Saccharomyces cerevisiae S288c (Q27510868)|Saccharomyces Genome Database ID (P3406)|Yes
C elegans|Caenorhabditis elegans (Q91703)|Propose: [Wormbase ID](http://www.wormbase.org)|No
drosophila|Drosophila melanogaster (Q130888)|Propose: [Flybase ID](http://flybase.org/)|No
Zebrafish|zebrafish (Q169444) (Danio rerio)| Propose: [ZFIN ID](https://zfin.org)|No
Mouse|Mus musculus (Q83310)|Mouse Genome Informatics ID (P671), MGI Gene Symbol (P2394) |Yes
Rat|brown rat (Q184224) (Rattus norvegicus)| Propose: [RGD ID](http://rgd.mcw.edu/) |Yes

**Comment by goodb** [comment]
fair to not worry about using identifiers for these resources despite their licenses...

**Comment by goodb** [comment]
all genomes loaded except arab.  has its own issue.

**Comment by stuppie** [comment]
http://tinyurl.com/kreqtet
