### ISSUE TITLE
load coriell cell line data

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#83]
similar to #47, can we load data on human cell lines as disease models from Coriell? Example record:

https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM14624&Product=CC

- [ ] First, need to model one item as demonstration
- [ ] Next, reach out to them to discuss licensing

**Comment by andrawaag** [comment]
Is this something that also aligns with the work done in cellosaurus? see: https://www.ncbi.nlm.nih.gov/pubmed/29805321

**Comment by andrewsu** [comment]
@sabahzero can you take the lead on step #1 above?

**Comment by sabahzero** [comment]
Per discussion with @andrewsu after further exploring the relations of this issue with cellosaurus RE @andrawaag 's inquiry, we've determined this as resolved 

See example under 'established from medical condition' Statement + 'Cellosaurus ID' Identifier
https://www.wikidata.org/wiki/Q54847344
