### ISSUE TITLE
Something wrong with GO Bot?

### ISSUE THREAD

**Issue by stuppie** [SuLab/GeneWikiCentral#85]
We now have regulation of leucine import across plasma membrane (Q27303095) subclass of regulation of leucine import (Q22303228), which is in turn a subclass of regulation of leucine import across plasma membrane (Q27303095) thanks to your recent edits - in this case both relations are referenced to "Gene Ontology", the first dated 9 May 2017, and the second dated 6 March 2018. The new relation doesn't make sense to me given the labels - maybe something's gone wrong with the ID's?

https://www.wikidata.org/wiki/User_talk:ProteinBoxBot#More_subclass_loops_from_imported_ontologies

**Comment by sebotic** [comment]
Do you have any more details on the issue? Is it an issue with import code or issue with updating the existing Ontology structure in WD? Or an issue with pruning of outdated relations in the ontologies? For the GO bot, as far as I recall, I had pruning implemented

**Comment by sebotic** [comment]
apparently, GO replaced all is_a relations of this term https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1905532 and this has not been appropriately been captured (https://www.wikidata.org/wiki/Q27303095) 

dont know why, yet

**Comment by sebotic** [comment]
with this commit (https://github.com/SuLab/scheduled-bots/commit/c1de5954f00aaf8938efe11d0f16042b35bb4102#diff-37fb5cf28c5e38f1286608c90c83deb5) you introduced append for P279, so obsolete is_a wont get overwritten anymore. Could that be one reason

**Comment by stuppie** [comment]
Yes, this commit was introduced because the bot was overwriting other people's 'subclass of' statements (https://www.wikidata.org/wiki/User_talk:ProteinBoxBot#Do_not_remove_statements_automatically_created_by_other_users), and so it now shouldn't overwrite them. I see now the pruning now needs to be fixed to remove the old statements, but keeping other people's statements..

**Comment by sebotic** [comment]
yes, that's going to be slightly complicated to implement. Bc first we need to determine who contributed what. How many useful and valid contributions to GO and DO did you encounter so far?

**Comment by stuppie** [comment]
There are many useful and valid contributions, but either way, we shouldn't overwrite other people statements automatically. I've implemented this with the DO bot. 
https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/disease_ontology/DOID_obographs_bot.py

It first updates the references on existing statements to use the new release (with "stated in"), and then afterwards, goes through and only removes statements with the old DO release.

**Comment by stuppie** [comment]
Issue is (I hope) fixed now.
Code: https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/ontology/obographs_GO.py
Example revision: https://www.wikidata.org/w/index.php?title=Q177708&type=revision&diff=677304566&oldid=676928965 ('part of' was updated without touching 'human development')

**Comment by sebotic** [comment]
looks good, using obographs seems like a clever solution
