### ISSUE TITLE
broken example on SPARQL Examples page

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#88]
This query https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples#Which_variant_of_which_gene_predicts_a_positive_prognosis_in_colorectal_cancer returns zero results.  We should either update/add data so that it is a nonzero result, or update the query to highlight other data types. Also, the table shown below the sparql query is presumably supposed to show the current results of the sparql query, but that must be failing for some reason (perhaps because the query is returning zero results?).

**Comment by stuppie** [comment]
There's no prognostic predictors at all! 
https://tools.wmflabs.org/sqid/#/view?id=P3358&lang=en
Not sure where they went... @andrawaag Are these all removed since the non-clinical non-high quality statements were removed?

**Comment by stuppie** [comment]
And yes, this also seems like a ListeriaBot bug. When you run it, it says "No items", and so it doesn't update the table..

**Comment by andrawaag** [comment]
@stuppie I actually don't know, but I am on it.

**Comment by andrawaag** [comment]
Looks a bit more difficult than I anticipated. I think the civic bot needs to generate a summary of what was added. I will try to add that and do a custom run

**Comment by stuppie** [comment]
Updated bot. See above issue.
