### ISSUE TITLE
PBB overwriting human GO annotations

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#89]
PBB is overwriting some human-added GO annotations for the chlambase project:
https://www.wikidata.org/w/index.php?title=Q21168330&type=revision&diff=669391630&oldid=667802167

Would be great if we could undo those changes automatically (though the chlambase edits are few enough such that it could be manually undone by hand if necessary).

Related issue: https://www.wikidata.org/wiki/User_talk:ProteinBoxBot#Do_not_remove_statements_automatically_created_by_other_users

cc @djow2019

**Comment by stuppie** [comment]
see also #85 
I'm going to switch to using [this](https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/ontology/obographs.py), but need to finish testing it. This should address both of these issues.

**Comment by stuppie** [comment]
Issue is (I hope) fixed now.
Code: https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/ontology/obographs_GO.py
Example revision: https://www.wikidata.org/w/index.php?title=Q177708&type=revision&diff=677304566&oldid=676928965 ('part of' was updated without touching 'human development')

**Comment by stuppie** [comment]
https://github.com/SuLab/scheduled-bots/commit/4265302ef977e79f9e9f27ebaea02f4206fb131b
