### ISSUE TITLE
EC number links not correct

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#92]
copied from https://github.com/SuLab/ChlamBase.org/issues/70: 

> For certain enzyme classes that have a single digit EC Number, the url is incorrect. See https://www.wikidata.org/wiki/Q14859873 (lyase activity). It links to https://enzyme.expasy.org/EC/4 when it should be https://enzyme.expasy.org/EC/4.-.-.- (padded with hyphens and periods at the end)

could either be the value that needs to be fixed, or the URL formatter

**Comment by stuppie** [comment]
Looking at the official EC documents ([link](http://www.sbcs.qmul.ac.uk/iubmb/enzyme/EC1/cont1aa.html)), it looks like the current format is correct and expasy just has a non-standard url format. In the wikidata external ID formatter there is no way to substitute periods or anything conditionally. The NC-IUBMB page ([example](http://www.sbcs.qmul.ac.uk/iubmb/enzyme/EC1/1/)) also requires conditional formatting (i.e. "EC 1.1" -> "EC1/1/") which is not doable with the wikidata formatter.

One workaround is this tool: https://tools.wmflabs.org/wikidata-externalid-url/
I can look into imlementing an EC fix using this as the formatter....

**Comment by stuppie** [comment]
Also see: https://phabricator.wikimedia.org/T150939 and Related Objects / Task Graph

**Comment by stuppie** [comment]
https://github.com/SuLab/scheduled-bots/commit/db50afd70071b61db59e0861f98246c289f81de0

https://www.wikidata.org/w/index.php?title=Q14859873&type=revision&diff=684988288&oldid=677252878
