### ISSUE TITLE
Editing rate limit for Cellosaurus Bot

### ISSUE THREAD

**Issue by LeliaDebornes** [SuLab/GeneWikiCentral#93]
Hello,

I develop a bot to integrate cell lines from Cellosaurus in Wikidata. 
This is the bot account <https://www.wikidata.org/wiki/User:CellosaurusBot>, and my request for a flag has been accepted. But I still limited when the bot run : 
error: "As an anti-abuse measure, you are limited from performing this action too many times in a short space of time, and you have exceeded this limit.\nPlease try again in a few minutes."

Does anyone know why I have this error?

You can see the bot code on GitHub: <https://github.com/calipho-sib/cellosaurus-wikidata-bot>

Thank-you,

**Comment by stuppie** [comment]
Hi Lelia,
Bots still have a rate-limit in place. See here: https://www.wikidata.org/wiki/Wikidata:Project_chat#Limit_page_creation_and_edit_rate
And see this issue in WDI: https://github.com/SuLab/WikidataIntegrator/issues/60
Please update wikidataintegrator. I implemented a feature to automatically wait and retry when you hit the rate limit.

**Comment by stuppie** [comment]
Lelia, Did this solve the issue? Please reopen if not

**Comment by LeliaDebornes** [comment]
Yes, it solved. 
Thank you very much!
